apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-endpoint-mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-endpoint-mongodb
  template:
    metadata:
      labels:
        app: go-endpoint-mongodb
    spec:
      containers:
      - name: go-endpoint-mongodb
        image: laielvin0/go-endpoint-mongodb:1.14
        ports: 
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@$(DATABASE_URL):27017/admin"
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: go-endpoint-mongodb-svc
spec:
  type: LoadBalancer
  selector:
    app: go-endpoint-mongodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080