apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-endpoints-mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-endpoints
        image: go-endpoints:1.0
        imagePullPolicy: Never
        ports: 
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-endpoint-service
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 

