apiVersion: v1
kind: Service
metadata:
  name: longhorn-svc
  namespace: longhorn-system
spec:
  type: LoadBalancer
  selector:
    app: longhorn-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
