apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-endpoint-mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-endpoint-mongodb
  template:
    metadata:
      labels:
        app: go-endpoint-mongodb
    spec:
      containers:
      - name: go-endpoint-mongodb
        image: laielvin0/go-endpoint-mongodb:1.14
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-endpoint-mongodb-svc
spec:
  type: LoadBalancer
  selector:
    app: go-endpoint-mongodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080