apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-endpoint
  template:
    metadata:
      labels:
        app: go-endpoint
    spec:
      containers:
      - name: go-endpoint
        image: go-endpoint:1.0
        imagePullPolicy: Never
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-endpoint-service
spec:
  selector:
    app: go-endpoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer 

